-- liquibase formatted sql
-- changeset tagcloud:update_db_core_rss-2.1.9-2.2.0.sql
-- preconditions onFail:MARK_RAN onError:WARN
-- XSL portlet ported to HTML in v8 (mvc-patterns.md 10): the stylesheet
-- inserts were removed, those tables no longer exist in the core.
